### ISSUE TITLE
Обратная конвертация правил srs.

### ISSUE THREAD

**Issue by burjuyz** [Dunamis4tw/generate-geoip-geosite#2]
Вы не могли бы еще сделать обратную конвертацию правил srs в json к примеру, чтоб можно было смотреть другие правила и какие адреса там присутствуют.

**Comment by Dunamis4tw** [comment]
Я точно не помню, но вроде бы это умеет делать сам клиент sing-box'а. Если он этого не умеет, я уже вряд-ли смогу написать этот функционал, так как даже конвертация json в srs происходит благодаря коду из sing-box'а, который я просто импортирую в свой проект. Я структуру srs файла не изучал, и понятия не имею как он хранит там домены.

**Comment by Dunamis4tw** [comment]
Нет, к сожалению srs в json sing-box не умеет конвертировать. Видимо я перепутал с geosite, так как его он может экспортировать в список:
```bash
sing-box.exe geosite
Geosite tools

Usage:
  sing-box geosite [command]

Available Commands:
  export      Export geosite category as rule-set
  list        List geosite categories
  lookup      Check if a domain is in the geosite
```
И к сожалению ничего подобного я не вижу у rule-set (в [Sing-box 1.8.2](https://github.com/SagerNet/sing-box/releases/tag/v1.8.2)):
```bash
sing-box.exe rule-set
Manage rule sets

Usage:
  sing-box rule-set [command]

Available Commands:
  compile     Compile rule-set json to binary
  format      Format rule-set json
```

**Comment by Dunamis4tw** [comment]
Тут либо разработчика sing-box'а просить, либо я могу попытаться разобраться в формате srs файла, и если будет не сложно, может и смогу написать конвертер. Но ничего не обещаю)
