### ISSUE TITLE
Формирование листов формата .dat

### ISSUE THREAD

**Issue by burjuyz** [Dunamis4tw/generate-geoip-geosite#4]
Появилась идея добавить формирование листов формата .dat, что позволит на сервере использовать в следующих сценариях: 

>  "routing": {
>         "domainStrategy": "IPIfNonMatch",
>         "rules": [
>             {
>                 "type": "field",
>                 "outboundTag": "BLOCK",
>                 "domain": [
>                     "geosite:private",
>                     **"ext:block.dat:adg-ads"**
>                 ]
>             },

Что мы получаем, скорость обработки выше чем через всякие Ad-Guard Home и Pi-Hole. Ресурсов  тратится меньше. Нет беcполезного перегона трафика. Реклама режется на 73-75% % от номинала, что для DNS фильтра очень хорошо.

Я думаю Вам не составит труда добавить такую опцию, т.к. у вас библиотека на go и она позволяет это делать...

**Comment by zaskochill** [comment]
списки с доменами можно конвертировать с помощью https://github.com/v2fly/domain-list-community
списки с IP можно конвертировать с помощью: https://github.com/v2fly/geoip


Наверное, можно это будет применить здесь же в одном скрипте

**Comment by Dunamis4tw** [comment]
Я правильно понимаю, что у вас сервер работает на V2Ray, а клиент у вас сингбоксовский? И вы хотите, чтобы программа могла генерировать ещё и файлы для V2Ray?
В целом, с реализацией проблем быть не должно, раз оно тоже на Go написано.
А если не секрет, почему вы не используете сингбоксовский сервер? Он как и клиент, работает с рулсетами, и в целом также просто настраивается.

**Comment by Dunamis4tw** [comment]
И можно поподробнее про скорость? Почему вы решаете, что поставить правила блокировки на сервере лучше, чем на клиенте?

**Comment by burjuyz** [comment]
Не, сервер у меня не V2Ray, но эта опция будет полезна и тем кто пользуется и сингбоксом, и xray, и vray. 
Про скорость имелось ввиду, что не надо еще ставить доп. приложение на сервере в виде adguard и Pihole и гонять трафик между ними, в таком случае на клиентах бы всех помимо сингбокса будет резаться реклама. 

Формат .dat удобен тем, что в него можно загнать несколько списков и использовать 1 файл  в котором будут и списки антирекламы и списки торрента и еще какие то, один файл в котором один список может идти в direct, а другой в block...
у списков srs принцип другой, дробить большие списки на мелкие... 

Хотелось бы получить один инструмент который бы генерировал бы разные списки сразу под разные задачи и под разные решения.

Чтоб по итогу загнать ваш парсер в github action и чтоб он в авторежиме генерировал разные списки...

**Comment by zaskochill** [comment]
В некоторых случаях может потребоваться использование и .dat и .srs списков.
Пользователю в зависимости от его user agent приложения (sing-box или v2ray) можно отдавать разные конфигурации в подписке. Соответственно, нужны списки и того и того формата.

Например, я хочу сделать список для блокировки торрентов в формате .dat. Что мне для этого сейчас нужно сделать:
1) Сделать парсинг списков в нужном виде, чтобы были только домены. Для этого можно использовать ваш скрипт. Получаем .lst список и srs для синг-бокса
2) Затем этот список прогоняем через https://github.com/v2fly/domain-list-community и получаем из .lst списка список формата .dat

Затем, если хочу получить .dat список с IP адресами, я иду в третий скрипт:
https://github.com/v2fly/geoip

Как правило, списки с IP в интернете уже имеют нормальный вид и их можно сразу прогнать здесь.

Что имеем: чтобы сделать список доменов и список IP, нужно подключать 3 скрипта. Чтобы это всё автоматизировать, нужно работать сразу с 3 скриптами :)

По этой причине, хотелось бы иметь инструмент "2 в 1", чтобы ввести список источников и получить все списки в одном месте

**Comment by zaskochill** [comment]
Также, есть предложение, которое может сделать работу с большим количеством списков удобнее. Так реализовано в скрипте для работы с geoip здесь:
https://github.com/v2fly/geoip

Там скрипт запускается сразу через go run ./ , а работа со списками идёт через файл config.json:
[config-example.json](https://github.com/v2fly/geoip/blob/master/config-example.json)

Если мы работаем с разными форматами списков, это было бы более удобно, чем заводить под каждую категорию  списков json файл с источниками дланных и потом вводить под каждый json файл команду. Как реализовано там:

В конфиге прописывается 2 раздела: input и ouptut. 

>**В input кладёт все наши списки. Списки можно добавлять как по URL адресу, так и прописывать непосредственно путь на сервере.**

Например:
```
{
"input": [
  {
    "type": "text",
    "action": "add",
    "args": {
      "name": "СПИСОК1",
      "uri": "https://URL.txt",
      "onlyIPType": "ipv4"
    }
  },
  {
    "type": "v2rayGeoIPDat",
    "action": "add",
    "args": {
      "uri": "./СПИСОК2.dat",
      "wantedList": ["cn", "us"],
      "onlyIPType": "ipv4"
    }
  },
  {
    "type": "text",
    "action": "add",
    "args": {
      "inputDir": "./data"
    }
  }
  ```
  Получаем в источники данных:
  СПИСОК1.txt, СПИСОК2.dat:cn, СПИСОК2.dat:us и все списки из папки /data
  
>**В output задаем правила, из каких списков какие списки делать, в каком формате и куда затем их класть.
Формат dat может в одном списке содержать несколько подсписков. Например, geoip:ru, geoip:cn**

Соответственно, можно взять список test1.lst и test2.lst и сконвертировать в final.dat
И затем, обращаться к обеим спискам через final.dat:test1.lst и final.dat:test2.lst

Например:

Преобразует все списки из INPUT в формат .dat в отдельные списки (т.к. установлено         "oneFilePerList": true)
```
{
      "type": "v2rayGeoIPDat",
      "action": "output",
      "args": {
        "oneFilePerList": true
      }
    },
```

Возьмёт список1 из INPUT, список 2 из INPUT и отправит их вместе в СПИСОК1_СПИСОК2.dat
```
{
      "type": "v2rayGeoIPDat",
      "action": "output",
      "args": {
        "outputName": "СПИСОК1_СПИСОК2.dat",
        "wantedList": ["СПИСОК1", "СПИСОК2"]
      }
    },
```

Если не указывать списки, которые брать, то возьмёт все списки из INPUT все их отправит в один .dat файл ALL.dat:
```
{
      "type": "v2rayGeoIPDat",
      "action": "output",
      "args": {
        "outputName": "ALL.dat"
      }
    }
```    
   По итогу, мы могли бы в один конфигурационный файл вставить все свои списки (торренты, реклама, антизапрет и .т.д.), затем указать в OUTPUT какие списки хотим получить и запустить это всё одной командой. При этом, не нужно хранить под каждый источник отдельные json файлы. Только сами списки, если берем их с сервера. Если берем из интернета, то вообще ничего не нужно, кроме скрипта и файла конфига.

**Comment by zaskochill** [comment]
То есть, по примеру выше, имея один файл config.json в таком виде, мы загрузим 1 список с торрентами, 2 список с adaway рекламой и на выходе получим 2 отдельных .dat списка с торрентами, 1 список с рекламой adaway и все списки в формате .srs (если не указывать "wantedList" с конкретными списками
```
{
"input": [
  {
    "type": "text",
    "action": "add",
    "args": {
      "name": "torrent_trackers",
      "uri": "https://raw.githubusercontent.com/im-sm/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt",
    }
  },
  {
    "type": "text",
    "action": "add",
    "args": {
      "name": "torrent_websites",
      "uri": "https://raw.githubusercontent.com/im-sm/Pi-hole-Torrent-Blocklist/main/all-torrent-websites.txt",
    }
  },
  {
    "type": "text",
    "action": "add",
    "args": {
      "name": "adaway",
      "uri": "https://schakal.ru/hosts/hosts.txt",
    }
  }
],
  "output": [
    {
      "type": "v2rayGeoIPDat",
      "action": "output",
      "args": {
        "outputDir": "./torrents",
        "wantedList": ["torrent_trackers", "torrent_websites"],
        "oneFilePerList": true
      }
    },
    {
      "type": "v2rayGeoIPDat",
      "action": "output",
      "args": {
        "outputName": "adaway.dat",
        "outputDir": "./adaway",
        "wantedList": ["adaway"]
      }
    },
    {
    "type": "srs",
    "action": "output",
    "args": {
      "outputDir": "./srs"
    }
  ]
}
```

Мне кажется, этот способ был бы очень удобный, если работать с разными форматами списков в большом количестве

**Comment by Dunamis4tw** [comment]
По поводу генерации .dat файла, посмотрю в выходные что можно сделать с этим. Идея добавить этот формат мне нравится.

А что по поводу конфиг файла, почти весь этот функционал реализуем и с моей реализацией source файлов. Следующий source файл сделает всё тоже самое:
```json
[
  {
    "url": "https://raw.githubusercontent.com/im-sm/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt",
    "contentType": "DefaultList",
    "category": "torrent_trackers"
  },
  {
    "url": "https://raw.githubusercontent.com/im-sm/Pi-hole-Torrent-Blocklist/main/all-torrent-trackres.txt",
    "contentType": "DefaultList",
    "category": "torrent_websites"
  },
  {
    "url": "https://schakal.ru/hosts/hosts.txt",
    "contentType": "HostsFile",
    "category": "adaway"
  }
]
```
Вот что в итоге получается в папке после выполнения команды `generate-geoip-geosite.exe -s sourceTest.json -o test -i test`:
```
test\geoip.db
test\geosite.db
test\include-domain-adaway.lst
test\include-domain-torrent_trackers.lst
test\include-domain-torrent_websites.lst
test\ruleset-domain-adaway.json
test\ruleset-domain-adaway.srs
test\ruleset-domain-torrent_trackers.json
test\ruleset-domain-torrent_trackers.srs
test\ruleset-domain-torrent_websites.json
test\ruleset-domain-torrent_websites.srs
```

Единственное, что не получится сделать, отдельные geoip и geosite для каждой категории. Но по сути, это мало кому нужно, и суть этих файлов как раз в том, что все категории хранятся в 1 файле.

Ещё не знаю как буду реализовывать генерацию dat файлов, но походу надо будет думать над тем, генерировать один общий dat файл со всеми категориями, или для каждой категории отдельный dat файл. Возможно реализую так, чтобы и то и то генерировалось.

Как я понимаю конфиг, который вы предлагаете реализовать, позволяет настраивать более тонко куда пойдёт та или иная категория, и какие в итоге файлы будут сгенерированы. Тут соглашусь, но я в своей реализации пытался как можно больше уйти от конфигов, чтобы всё можно было сделать в консоли.

Source-файлы по сути - просто массив источников, в который, как предполагалось, вы закинете вообще всевозможные списки. И затем одной командой вы сгенерируете всевозможные файлы, которые поддерживает программа. Вам же никто не мешает взять и объединить все source файлы из репозитория в один большой source-файл со всеми категориями.

Если необходимо сгенерировать из списка, который лежит не в инете, а на диске, то перед генерацией его нужно положить в папку, которую вы указываете в `-i /example`. Ну и естественно нужно назвать соответствующе, чтобы программа поняла что делать с этим файлом.

Изначальная идея программы была - сделать генератор всего из всего, чтобы потом это публиковать в отдельной репе на гитхабе. А дальше уже за пользователем было решать, какой список и как его использовать ему.

Если делать вашу систему конфигов, то это надо будет переписать бОльшую часть программы) Так что, не думаю что буду это делать.

Спасибо за подробное пояснение как работает конфиг файл генератора для v2ray. Раньше видел этот репозиторий, но так и не дошли руки разобраться в их конфиге. Да и к тому же, я ни разу не имел дело с v2ray.

**Comment by zaskochill** [comment]
То, что можно все списки вставить в один файл это понятно. Но тогда мы будем просто иметь каждый список во всех форматах. Это получается не настраиваемо и не гибко.

А в том формате, который я привёл можно через input и output настраивать любые форматы в любом виде. Как только сам разобрался в этом конфиге, понял насколькр это удобно. Особенно, учитывая то, что у нас .dat может содержать в себе несколько списков внутри.

Если я хочу объединить 2 списка с торрентами в один .dat, 2 списка с рекламой в другой .dat, а другие 4 файла в отдельные .dat файлы? Мне все равно придется разделять источники на отдельные списки в вашем случае. Либо будет просто много отдельных .dat списков, если делать каждый список отдельно в .dat файл.

Т.е., имея конфигурацию с input и output, можно было бы вводить и выводить списки в любом формате, в любой связке и это было бы очень удобно. 
Очень жаль, что не планируется это реализовать :(

**Comment by Dunamis4tw** [comment]
Добавил возможность генерировать .dat файлы, пока только с доменами, с IP не разбирался ещё. Проверить нет возможности, так как никогда раньше не сталкивался с xray/v2ray и не знаю как его настраивать. Поэтому надеюсь на вашу помощь:

- [v1.4.0-alpha.1](https://github.com/Dunamis4tw/generate-geoip-geosite/releases/tag/v1.4.0-alpha.1)

Пока что альфа версия, так как не понятно, будет ли работать сгенерированный dat файл. Плюс ещё много чего надо будет допилить.
Можете помочь с пониманием как можно использовать эти dat файлы?
- Как я понял, это по сути те же geoip.db и geosite.db, только в другом виде?
- Можно ли засунуть в один dat файл и IP и домены?
- Можно ли в xray/v2ray использовать два разных dat файла, один с ip адресами, а другой с доменами? Спрашиваю, потому что NekoBox, например, не может работать с двумя разными geoip или geosite. _(Собственно, изначально и была идея создать эту программу, которая бы генерировала один geoip и один geosite с нужными мне категориями, а уже потом добавили более удобные рулсеты и вообще я планирую отказаться от nekobox в сторону обычного singbox)_
