### ISSUE TITLE
Возможность генерирования файлов из локальных списков

### ISSUE THREAD

**Issue by 1andrevich** [Dunamis4tw/generate-geoip-geosite#6]
Добрый день! Спасибо за вашу программу, не хватает возможности генерировать файлы из локальных списков, возможна она есть, но не понял как ей воспользоваться

**Comment by Dunamis4tw** [comment]
Добрый. Возможность есть, вам необходимо в отдельной папке, например "/mypath" создать файлик формата `{include/exclude}-{ip/domain}-{category_name}.{lst/rgx}`, например include-domain-mycategory.lst. В этот файлик записываем домены (один на строчку). И затем запускаем программу с параметрами `generate-geoip-geosite -i /mypath -o /mypath`. В итоге сгенерируются всевозможные файлы и положатся в эту же папку /mypath. А скачивание и конвертирование это уже доп. возможность, и она не обязательна.

**Comment by 1andrevich** [comment]
Спасибо большое, видимо пропустил это
